public: true
type: "docs"
category: "collection development and management"
tags:
      "workflow"
title: "Guide for Digital Transfer"
description: "A guide for transferring digital records"
pages:
  - ["Guide for Digital Transfer", "index"]
